# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: 89089634+lifafa03@users.noreply.github.com
author_name: lifafa03
preset_name: starter
project_name: easy-a-hackathon-frontend

