# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: 89089634+lifafa03@users.noreply.github.com
author_name: lifafa03
contract_name: smart_contract
preset_name: starter
project_name: easy-a-hackathon

